import fs from 'node:fs/promises';
const target='wordpress/qav-advocate';
const html=await fs.readFile('index.html','utf8');
const asset=s=>s.replace(/(src|href)="(assets\/[^" ]+)"/g,`$1="<?php echo esc_url(qav_asset('$2')); ?>"`);
const links=s=>s.replace(/href="#(?!icon-|main|disclaimer)([\w-]+)"/g,`href="<?php echo esc_url(qav_home_anchor('$1')); ?>"`).replaceAll('href="insights.html"','href="<?php echo esc_url(qav_insights_url()); ?>"').replaceAll('href="media.html"','href="<?php echo esc_url(qav_media_url()); ?>"').replaceAll('href="privacy.html"','href="<?php echo esc_url(home_url(\'/privacy/\')); ?>"');
const contact=s=>s.replaceAll('mailto:wicky.mechanier1446@gmail.com',"mailto:<?php echo esc_attr(qav_profile('email')); ?>").replaceAll('wicky.mechanier1446@gmail.com',"<?php echo esc_attr(qav_profile('email')); ?>").replaceAll('tel:+923137277355',"<?php echo esc_url(qav_tel('phone')); ?>").replaceAll('tel:+923035980803',"<?php echo esc_url(qav_tel('phone_secondary')); ?>").replaceAll('+92 313 7277355',"<?php echo esc_html(qav_profile('phone')); ?>").replaceAll('+92 303 5980803',"<?php echo esc_html(qav_profile('phone_secondary')); ?>").replace(/4B One Lahore, Qurban Police Lines,[\s\S]{0,35}?Jail Road, Lahore/g,"<?php echo nl2br(esc_html(qav_profile('address'))); ?>");
let header=html.slice(html.indexOf('<a class="skip-link"'),html.indexOf('<main id="main"'));
header=links(header);
// Keep the global mobile menu on the native hub URL, including on nested pages.
header=header.replace(/<nav aria-label="Mobile navigation">[\s\S]*?<\/nav>/,mobile=>mobile.replace('<a href="insights-media.html">Insights &amp; Media</a>','<?php qav_hub_nav(); ?>'));
// Archive links in the desktop navigation are direct, so both archives remain discoverable.
header=header.replace('<a href="<?php echo esc_url(qav_home_anchor(\'insights\')); ?>">Insights &amp; Media</a>','<a href="<?php echo esc_url(qav_insights_url()); ?>">Insights</a><a href="<?php echo esc_url(qav_media_url()); ?>">Media</a>');
await fs.writeFile(`${target}/header.php`,`<?php if (!defined('ABSPATH')) exit; ?><!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#061a2f"><link rel="icon" type="image/svg+xml" href="<?php echo esc_url(qav_asset('assets/svg/favicon.svg')); ?>"><link rel="preload" href="<?php echo esc_url(qav_asset('assets/fonts/cormorant-garamond-medium.woff2')); ?>" as="font" type="font/woff2" crossorigin><link rel="preload" href="<?php echo esc_url(qav_asset('assets/fonts/manrope-variable.woff2')); ?>" as="font" type="font/woff2" crossorigin><?php wp_head(); ?></head><body <?php body_class(); ?>><?php wp_body_open(); ?>${header}`);
let main=html.slice(html.indexOf('<main id="main"'),html.indexOf('<footer class="site-footer'));
main=main.replace(/<picture class="client-portrait">[\s\S]*?<\/picture>/,'<?php qav_portrait(true); ?>');
for(const [kind,type] of [['INSIGHTS','post'],['MEDIA','qav_media']])main=main.replace(new RegExp(`<!-- QAV_${kind}_START -->[\\s\\S]*?<!-- QAV_${kind}_END -->`),`<?php qav_home_publications('${type}'); ?>`);
main=contact(links(asset(main)));
const advisory=main.indexOf('class="section advisory-section"');
const practiceEnd=main.lastIndexOf('</div>',main.lastIndexOf('</section>',advisory));
main=main.slice(0,practiceEnd)+"<?php qav_practice_insights(); ?>"+main.slice(practiceEnd);
await fs.writeFile(`${target}/front-page.php`,`<?php get_header(); ?>${main}<?php get_footer(); ?>`);
let footer=html.slice(html.indexOf('<footer class="site-footer'),html.indexOf('</body>'));
footer=contact(links(footer));
await fs.writeFile(`${target}/footer.php`,`${footer}<?php wp_footer(); ?></body></html>`);
let privacy=await fs.readFile('privacy.html','utf8');privacy=privacy.slice(privacy.indexOf('<main'),privacy.indexOf('</main>')+7).replaceAll('href="index.html#contact"','href="<?php echo esc_url(qav_home_anchor(\'contact\')); ?>"');
await fs.writeFile(`${target}/page-privacy.php`,`<?php get_header(); ?>${contact(privacy)}<?php get_footer(); ?>`);
const base=await fs.readFile('style.css','utf8');
await fs.writeFile(`${target}/style.css`,`/*\nTheme Name: Qurat-ul-Ain Viirk — Advocate\nAuthor: QAV Website\nDescription: An editorial legal practice theme with Insights and Media publishing.\nVersion: 1.0.0\nRequires at least: 6.6\nRequires PHP: 8.1\nLicense: GPL-2.0-or-later\nText Domain: qav-advocate\n*/\n${base}`);
for(const name of ['upgrade.css','script.js'])await fs.copyFile(name,`${target}/${name}`);
await fs.cp('assets',`${target}/assets`,{recursive:true,filter:src=>!src.endsWith('master.jpeg')});
console.log('WordPress theme templates and assets generated.');
